services:
  - type: web
    name: context-reader
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HUGGING_FACE_API_KEY
        sync: false
      - key: AUTH0_SECRET
        sync: false
      - key: AUTH0_BASE_URL
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: context-reader-db
          property: connectionString

  - type: postgres
    name: context-reader-db
    plan: free
    ipAllowList: []
    postDeploy: npm run prisma:deploy
